// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PaydayController.Persistencia;

namespace PaydayController.Migrations
{
    [DbContext(typeof(ContextoFinanzas))]
    [Migration("20210914205341_MigracionPayday")]
    partial class MigracionPayday
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("PaydayController.Modelos.Saldo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime?>("Fecha")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("SaldoGuid")
                        .HasColumnType("text");

                    b.Property<float>("SaldoUsuario")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Saldos");
                });

            modelBuilder.Entity("PaydayController.Modelos.SaldoHistorico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Fuente")
                        .HasColumnType("text");

                    b.Property<float>("Saldo")
                        .HasColumnType("real");

                    b.Property<string>("SaldoHistoricoGuid")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SaldoHistoricos");
                });
#pragma warning restore 612, 618
        }
    }
}
